c_compiler:            # [osx]
  - clang_bootstrap    # [osx]
cxx_compiler:          # [osx]
  - clang_bootstrap    # [osx]

github_actions_labels:              # [win]
  - cirun-azure-windows-2xlarge     # [win]

channel_targets:
  - conda-forge llvm_rc
